### ISSUE TITLE
Code Solutions for Phase 1 Using Array Reduce

### ISSUE THREAD

**Issue by VernC** [learn-co-curriculum/phase-1-using-array-reduce#2]
### Canvas Link

https://github.com/VernC/phase-1-using-array-reduce

### Concern

When doing the test for the Phase 1 Using Array Reduce lab one of the possible coding solutions that should work for it doesn't. It works when it's run through a console and when I run it through Riplit.
![image](https://user-images.githubusercontent.com/87920842/140433309-3151ed8a-d94f-4e55-8bca-a706a9a9a295.png)

### Additional Context

I've attached an example of this code working in the console and on Riplit here. 
![image](https://user-images.githubusercontent.com/87920842/140433937-ed8ca3b1-50ce-41d0-843e-9bfe06d85b4e.png)
![image](https://user-images.githubusercontent.com/87920842/140434211-498b4cef-94e1-4a21-beb9-9efcba2d8a40.png)

**Comment by graciemcguire** [comment]
Hi @VernC ! Thanks for raising this issue. I see where you were going with this, but the reason the test isn't passing is because `totalBatteries()` should be returning the reduced amount of batteries not the function itself reduced. 
If you change your original totalBatteries to totalBatteriesFn, and then pass that into a new totalBatteries it should pass all your tests. 
```js
const batteryBatches = [4, 5, 3, 4, 4, 6, 5];

const totalBatteriesFn = (previousValue, currentValue) => previousValue + currentValue;

const totalBatteries = batteryBatches.reduce(totalBatteriesFn)
```
Hope this helps, and happy coding!
